# conda env create -f environment.yml
# conda env remove --name dashtut
name: dashtut
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.7.6
    - pip=20.0.2
    - bottleneck=1.3.2
    - numpy=1.18.1
    - pandas=1.0.1
    - scikit-learn=0.22.1
    - xlrd=1.2.0
    - xlwt=1.3.0
    